version: '5.1.4'
services:
  app1: 
    image: my-app:latest
    environment:
      - APP_NAME=App1
    ports:
      - 5000:3000
  app2: 
    image: my-app:latest
    environment:
      - APP_NAME=App2
    ports:
      - 5001:3000


  app3: 
    image: my-app:latest
    environment:
      - APP_NAME=App3
    ports:
      - 5002:3000